# Generated by Django 4.2.7 on 2023-12-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Borrowing_Book'), (3, 'Return_Book')], null=True),
        ),
    ]
